"""
group_algebra.jl — Two-block group-algebra (2BGA) codes for arbitrary finite groups.

Mirrors `research/kit/group_algebra.py` (Lin & Pryadko, arXiv:2306.16400).

Construction:
  G a finite group, |G|=N. Pick supports a,b ⊆ G.
  L(g) = left-regular permutation:  L(g) e_h = e_{g·h}
  R(g) = right-regular permutation: R(g) e_h = e_{h·g}
  L(a)=Σ_{g∈a}L(g),  R(b)=Σ_{g∈b}R(g)
  H_X=[L(a) | R(b)], H_Z=[R(b)ᵀ | L(a)ᵀ],  n=2N

CSS is automatic: left and right actions commute, so H_X·H_Zᵀ=0 mod 2.

Group encoding:
  Cayley table `mul` is N×N Int matrix, 1-indexed, identity at index 1.
  `mul[i,j]` = index of gᵢ·gⱼ. Built from permutation generators via
  `perm_group` or the helpers (`cyclic_group`, `dihedral_group`, `metacyclic`, …).
  Elements are stored as permutation vectors `Vector{Int}` 1-indexed on 1:degree.

Public:
  - `cyclic_group(n)`, `cyclic_product(orders...)`, `dihedral_group(n)`,
    `metacyclic(n,k,r)`, `sym_group(n)`, `alt_group(n)`, `perm_group(gens, degree)`
  - `perm_matrix(p)`, `left_regular_rep(mul,g)`, `right_regular_rep(mul,g)`
  - `build_2bga(mul, a, b)` / `build_2bga((mul,elems), a, b)` → (Hx,Hz)
"""

using SparseArrays

# ---------------------------------------------------------------------------
# Permutation helpers (1-indexed)
# ---------------------------------------------------------------------------

"""    _compose(p, q) -> Vector{Int}

Permutation composition (p ∘ q)(i) = p[q[i]] — apply q then p.
Both `p`,`q` are `Vector{Int}` 1-indexed on 1:degree."""
function _compose(p::AbstractVector{Int}, q::AbstractVector{Int})::Vector{Int}
    return [p[q[i]] for i in 1:length(q)]
end

"""    perm_matrix(p) -> SparseMatrixCSC{Bool}

Permutation matrix for `p`: M[p[c], c] = 1."""
function perm_matrix(p::AbstractVector{Int})::SparseMatrixCSC{Bool,Int}
    N = length(p)
    return sparse(Vector{Int}(p), collect(1:N), fill(true, N), N, N)
end

# ---------------------------------------------------------------------------
# Group construction — Cayley table mul (N×N, 1-indexed, identity=1)
# ---------------------------------------------------------------------------

"""
    perm_group(gens, degree) -> (mul, elems)

Group generated by permutation `gens` (each `Vector{Int}` 1-indexed on 1:degree)
via BFS closure. Returns `(mul, elems)` where `mul[i,j]` is the index (1-based)
of gᵢ·gⱼ and `elems` is the element list (identity at index 1).
"""
function perm_group(gens::AbstractVector{<:AbstractVector{Int}}, degree::Int)
    isempty(gens) && error("perm_group: need at least one generator")
    ident = collect(1:degree)
    elems = Vector{Vector{Int}}()
    push!(elems, ident)
    index = Dict{Vector{Int},Int}(copy(ident) => 1)
    frontier = Vector{Vector{Int}}([ident])
    while !isempty(frontier)
        nxt = Vector{Vector{Int}}()
        for e in frontier, g in gens
            h = _compose(e, g)
            if !haskey(index, h)
                index[h] = length(elems) + 1
                push!(elems, h)
                push!(nxt, h)
            end
        end
        frontier = nxt
    end
    N = length(elems)
    mul = zeros(Int, N, N)
    for i in 1:N, j in 1:N
        mul[i, j] = index[_compose(elems[i], elems[j])]
    end
    return mul, elems
end

# single-arg vector convenience
perm_group(gens::AbstractVector{<:AbstractVector{Int}}) = perm_group(gens, length(gens[1]))

"""
    cyclic_group(n) -> (mul, elems)

Cyclic group C_n (order n) as a Cayley table. Identity at index 1.
"""
function cyclic_group(n::Int)
    r = vcat(collect(2:n), [1])  # n-cycle
    return perm_group([r], n)
end

"""
    cyclic_product(orders...) -> (mul, elems)

Abelian group Z_{o1} × … × Z_{ok} as a Cayley table. Identity at index 1.
On Z_l × Z_m this reproduces the `bb.jl` torus family.
"""
function cyclic_product(orders::Int...)
    @assert !isempty(orders) "need at least one order"
    tuples = Vector{Vector{Int}}()
    # cartesian product via recursion
    function rec(idx::Int, cur::Vector{Int})
        if idx > length(orders)
            push!(tuples, copy(cur))
            return
        end
        for v in 0:orders[idx]-1
            push!(cur, v)
            rec(idx + 1, cur)
            pop!(cur)
        end
    end
    rec(1, Int[])
    N = length(tuples)
    # map tuple -> index
    tmap = Dict{Vector{Int},Int}()
    for (i, t) in enumerate(tuples)
        tmap[t] = i
    end
    mul = zeros(Int, N, N)
    for i in 1:N, j in 1:N
        s = [(tuples[i][d] + tuples[j][d]) % orders[d] for d in 1:length(orders)]
        mul[i, j] = tmap[s]
    end
    return mul, tuples
end

"""
    direct_product(mulA, mulB) -> (mul, elems)

Cayley table of A × B.
"""
function direct_product(mulA::Matrix{Int}, mulB::Matrix{Int})
    a = size(mulA, 1)
    b = size(mulB, 1)
    N = a * b
    mul = zeros(Int, N, N)
    # index: (i,j) -> (i-1)*b + j  (1-indexed)
    for i in 1:a, j in 1:b, ii in 1:a, jj in 1:b
        mul[(i-1)*b+j, (ii-1)*b+jj] = (mulA[i, ii]-1)*b + mulB[j, jj]
    end
    elems = [(i, j) for i in 1:a for j in 1:b]
    return mul, elems
end

"""
    metacyclic(n, k, r) -> (mul, elems)

Semidirect product C_n ⋊ C_k with action j: i ↦ r^j · i (mod n).
Requires r^k ≡ 1 (mod n). Elements (i,j) at index i*k+j+1; identity (0,0)=1.
Dihedral D_n = metacyclic(n, 2, n-1).
"""
function metacyclic(n::Int, k::Int, r::Int)
    @assert powermod(r, k, n) == 1 "r^k != 1 mod n: $r^$k mod $n = $(powermod(r,k,n))"
    rp = [powermod(r, j, n) for j in 0:k-1]
    idx(i, j) = mod(i, n) * k + mod(j, k) + 1
    N = n * k
    mul = zeros(Int, N, N)
    for i in 0:n-1, j in 0:k-1, ii in 0:n-1, jj in 0:k-1
        mul[idx(i, j), idx(ii, jj)] = idx(i + rp[j+1] * ii, j + jj)
    end
    elems = [(i, j) for i in 0:n-1 for j in 0:k-1]
    return mul, elems
end

"""
    dihedral_group(n) -> (mul, elems)

Dihedral group D_n of order 2n (rotation r, reflection s) on n points.
Presentation ⟨r,s | r^n=s²=1, srs=r⁻¹⟩.
"""
function dihedral_group(n::Int)
    r = vcat(collect(2:n), [1])  # i -> i+1 mod n
    s = Vector{Int}(undef, n)
    # 0-indexed s[i]=(-i) mod n; 1-indexed: s[1]=1, s[2]=n, s[3]=n-1, ...
    for i in 1:n
        s[i] = mod1(1 - (i - 1), n)  # 1-indexed modular
        # check: i=1->1, i=2->n, i=3->n-1 ...
    end
    # verify python mapping: s = (-i) mod n in 0-indexed => s[0]=0 => Julia s[1]=1 good
    return perm_group([r, s], n)
end

"""
    sym_group(n) -> (mul, elems)

Symmetric group S_n (order n!).
"""
function sym_group(n::Int)
    # transposition (0 1) -> Julia (1 2)
    cyc = collect(1:n)
    cyc[1], cyc[2] = 2, 1
    rot = vcat(collect(2:n), [1])
    return perm_group(Vector{Vector{Int}}([cyc, rot]), n)
end

"""
    alt_group(n) -> (mul, elems)

Alternating group A_n (order n!/2).
"""
function alt_group(n::Int)
    three = collect(1:n)
    # (0 1 2) -> Julia (1 2 3) cycle
    three[1], three[2], three[3] = 2, 3, 1
    longc = if isodd(n)
        vcat(collect(2:n), [1])
    else
        # [0] + [1+(i+1)%(n-1) for i in 0..n-2] in 0-indexed
        # 0-indexed longc[0]=0 fixed, rest is shift of 1..n-1
        tmp = collect(1:n)
        tmp[1] = 1
        for i in 2:n
            tmp[i] = 1 + mod(i - 2 + 1, n - 1) + 1  # messy; simpler: build 0-index then convert
        end
        # rebuild correctly via 0-index logic then convert to 1-indexed
        z = zeros(Int, n)
        # 0-indexed: longc[0]=0, longc[i]=1+( (i-1+1) % (n-1)) for i=1..n-1
        for i0 in 0:n-1
            if i0 == 0
                z[i0+1] = 0
            else
                z[i0+1] = 1 + mod((i0 - 1) + 1, n - 1)
            end
        end
        # convert 0-indexed perm z to 1-indexed
        [z[i] + 1 for i in 1:n]
    end
    return perm_group(Vector{Vector{Int}}([three, longc]), n)
end

# ---------------------------------------------------------------------------
# Regular representation helpers
# ---------------------------------------------------------------------------

"""    left_regular_rep(mul, g) -> SparseMatrixCSC{Bool}

Permutation matrix L(g): L(g)[g·h, h] = 1."""
function left_regular_rep(mul::Matrix{Int}, g::Int)::SparseMatrixCSC{Bool,Int}
    N = size(mul, 1)
    @assert 1 <= g <= N
    p = [mul[g, h] for h in 1:N]
    return perm_matrix(p)
end

"""    right_regular_rep(mul, g) -> SparseMatrixCSC{Bool}

Permutation matrix R(g): R(g)[h·g, h] = 1."""
function right_regular_rep(mul::Matrix{Int}, g::Int)::SparseMatrixCSC{Bool,Int}
    N = size(mul, 1)
    @assert 1 <= g <= N
    p = [mul[h, g] for h in 1:N]
    return perm_matrix(p)
end

# ---------------------------------------------------------------------------
# Block sum helper (mod 2, sparse, toggle semantics)
# ---------------------------------------------------------------------------

function _block_from_perms(perms::Vector{Vector{Int}}, m::Int)::SparseMatrixCSC{Bool,Int}
    # toggle set: (row,col) -> Bool
    pos = Dict{Tuple{Int,Int},Bool}()
    for p in perms
        for c in 1:m
            key = (p[c], c)
            pos[key] = !get(pos, key, false)
        end
    end
    I = Int[]; J = Int[]
    sizehint!(I, length(pos)); sizehint!(J, length(pos))
    for (k, v) in pos
        v || continue
        push!(I, k[1]); push!(J, k[2])
    end
    return sparse(I, J, fill(true, length(I)), m, m)
end

function _block_regular(mul::Matrix{Int}, terms::AbstractVector{Int}, side::Symbol)::SparseMatrixCSC{Bool,Int}
    N = size(mul, 1)
    perms = Vector{Vector{Int}}()
    for g in terms
        @assert 1 <= g <= N "group index $g out of range 1..$N"
        if side === :L
            push!(perms, [mul[g, h] for h in 1:N])
        else
            push!(perms, [mul[h, g] for h in 1:N])
        end
    end
    return _block_from_perms(perms, N)
end

# ---------------------------------------------------------------------------
# Public 2BGA builder
# ---------------------------------------------------------------------------

"""
    build_2bga(mul, a, b) -> (Hx, Hz)

Two-block group-algebra code from Cayley table `mul` (N×N, 1-indexed) with
`a, b` lists of element indices (1-based, identity=1). Returns `Hx, Hz` as
`SparseMatrixCSC{Bool}` of shape (N, 2N). CSS is guaranteed.

Also accepts `build_2bga((mul,elems), a, b)` or `build_2bga(G, a, b)` where
`G` is a `(mul, elems)` tuple from the group builders.

Element indices are 1-based (Julia convention); the Python kit uses 0-based.
Convert by adding 1 when porting Python examples.
"""
function build_2bga(mul::Matrix{Int}, a::AbstractVector{Int}, b::AbstractVector{Int})
    La = _block_regular(mul, collect(Int, a), :L)
    Rb = _block_regular(mul, collect(Int, b), :R)
    Hx = hcat(La, Rb)
    Hz = hcat(transpose(Rb), transpose(La))
    Hx = SparseMatrixCSC{Bool,Int}(sparse(Hx))
    Hz = SparseMatrixCSC{Bool,Int}(sparse(Hz))
    return Hx, Hz
end

# tuple overload
function build_2bga(G::Tuple{Matrix{Int},Any}, a::AbstractVector, b::AbstractVector)
    return build_2bga(G[1], collect(Int, a), collect(Int, b))
end

# vector-of-perms overload: if G is just a vector of perms (unlikely), error helpfully
function build_2bga(G::AbstractVector{<:AbstractVector{Int}}, a::AbstractVector, b::AbstractVector)
    error("build_2bga: pass the Cayley table `mul` (or `(mul,elems)` tuple) from dihedral_group/cyclic_product, not the perm list. Use `G, elems = dihedral_group(n); build_2bga(G, a, b)` with a,b as 1-based element indices.")
end

# ---------------------------------------------------------------------------
# TestItems
# ---------------------------------------------------------------------------

using TestItems

@testitem "GroupAlgebra: cyclic group basics" begin
    using SparseArrays
    mul, elems = cyclic_group(6)
    @test size(mul) == (6, 6)
    @test mul[1, :] == 1:6  # identity row
    @test mul[:, 1] == 1:6  # identity col
    # cyclic_product 6×6 should be abelian order 36
    mul2, _ = cyclic_product(6, 6)
    @test size(mul2) == (36, 36)
end

@testitem "GroupAlgebra: dihedral_group order" begin
    mul, _ = dihedral_group(6)
    @test size(mul) == (12, 12)
    mul2, _ = dihedral_group(12)
    @test size(mul2) == (24, 24)
end

@testitem "GroupAlgebra: metacyclic matches dihedral" begin
    mul_d, _ = dihedral_group(6)
    mul_m, _ = metacyclic(6, 2, 5)
    @test size(mul_d) == size(mul_m) == (12, 12)
    # both groups are isomorphic (D6); check they are groups of same order and CSS works
    # Cayley tables may differ by element ordering, so just verify 2BGA commutes on both
    a = [1, 2, 3]; b = [1, 4, 7]
    Hx, Hz = build_2bga(mul_d, a, b)
    @test verify_css(Hx, Hz)
    Hx2, Hz2 = build_2bga(mul_m, a, b)
    @test verify_css(Hz2, Hx2) || verify_css(Hx2, Hz2)
end

@testitem "GroupAlgebra: perm_matrix is permutation" begin
    p = [2, 3, 1]
    M = perm_matrix(p)
    @test size(M) == (3, 3)
    @test nnz(M) == 3
    @test Matrix(M) == Bool[0 0 1; 1 0 0; 0 1 0]
end

@testitem "GroupAlgebra: build_2bga commutes (non-abelian)" begin
    mul, _ = dihedral_group(6)  # order 12, n=24
    a = [1, 2, 3]; b = [1, 4, 6]
    Hx, Hz = build_2bga(mul, a, b)
    @test size(Hx) == (12, 24)
    @test size(Hz) == (12, 24)
    @test verify_css(Hx, Hz)
    k = compute_k(Hx, Hz)
    @test k >= 0
end

@testitem "GroupAlgebra: abelian 2BGA reproduces [[72,12,6]] k=12" begin
    # 2BGA on Z6×Z6 with gross-code supports must give k=12 and CSS
    # Python kit: a=[(3,0),(0,1),(0,2)], b=[(0,3),(1,0),(2,0)] 0-based indices
    mul, tuples = cyclic_product(6, 6)
    tmap = Dict(tuples[i] => i for i in 1:length(tuples))
    a = [tmap[[3, 0]], tmap[[0, 1]], tmap[[0, 2]]]
    b = [tmap[[0, 3]], tmap[[1, 0]], tmap[[2, 0]]]
    Hx, Hz = build_2bga(mul, a, b)
    @test size(Hx) == (36, 72)
    @test verify_css(Hx, Hz)
    @test compute_k(Hx, Hz) == 12
end

@testitem "GroupAlgebra: non-abelian odd k reachable" begin
    # Non-abelian 2BGA can reach odd k (impossible for abelian BB).
    # This test just verifies the plumbing: random dihedral 12 builds commute
    # and compute_k runs without error.
    using Random
    Random.seed!(0)
    mul, _ = dihedral_group(12)
    for trial in 1:20
        a = rand(1:24, 3); b = rand(1:24, 3)
        a = unique(a); b = unique(b)
        (length(a) < 3 || length(b) < 3) && continue
        Hx, Hz = build_2bga(mul, a, b)
        @test verify_css(Hx, Hz)
        k = compute_k(Hx, Hz)
        @test k >= 0
    end
    @test true
end
